(()=>{"use strict";let e;Object.fromEntries?e=Object.fromEntries:(e=e=>[...e].reduce(((e,[t,n])=>(e[t]=n,e)),{}),Object.fromEntries=e);let t=0;const n=[],a=()=>{const e=["debug"],n=["log"],a=["warn","info"],o=["error"],r=[...e,...n,...a,...o],i=o;t>=80&&i.push(...e),t>=60&&i.push(...n),t>=30&&i.push(...a),r.forEach((e=>s[e]=i.includes(e)?console[e].bind(console):()=>{}))},s={set:e=>{t=e,n.forEach((e=>{e(s,t)})),a()},get:()=>t,get verbose(){return(s.debug||(()=>{})).bind(console)},debug:()=>{},
log:()=>{},warn:()=>{},info:()=>{},error:()=>{},addChangeListener:e=>{n.push(e)}};a();const{AbortController:o,FileReader:r,TextDecoder:i,addEventListener:l,atob:c,btoa:d,clearInterval:g,clearTimeout:m,crypto:u,decodeURIComponent:f,encodeURIComponent:h,escape:p,fetch:y,location:w,removeEventListener:b,setInterval:v,setTimeout:E,unescape:V}=self,{DOMParser:O,Notification:j,Image:k,Worker:P,XMLHttpRequest:S,alert:I,confirm:L,document:N,localStorage:M,screen:A}=(w.origin,w.host,
self),C="chromeStorage",D="version",T="schema",W="config",x="session",J=(()=>{const e=[D],t={};return e.forEach((e=>{t[e]=!0})),{keys:e,has:function(e){return!!t[e]}}})(),{storage:_,runtime:R}=chrome,q=async function(e,t){const n=F[e][t];n&&await n()},z=(()=>{let e=!1,t={};const n="normal",a={setValue:async(e,a)=>{const s=e;t[s]=a;const o={};o[s]={origin:n,value:a},await new Promise((e=>_.local.set(o,(()=>e()))))},setValues:async e=>{const a={};Object.keys(e).forEach((s=>{const o=s,r=e[s]
;t[o]=r,a[o]={origin:n,value:r}})),await new Promise((e=>_.local.set(a,(()=>e()))))},getValue:(e,n)=>{const a=e;return void 0===t[a]?n:t[a]},deleteAll:async()=>{const e=((e,t)=>{const n={};for(const a of t){const t=e.getValue(a);void 0!==t&&(n[a]=t)}return n})(a,J.keys);t=e,await new Promise((t=>{_.local.clear((async()=>{await(async(e,t)=>{await Promise.all(Object.getOwnPropertyNames(t).map((async n=>{void 0!==t[n]&&await e.setValue(n,t[n])})))})(a,e),t()}))}))},deleteValue:async e=>{const n=e
;delete t[n],await new Promise((e=>_.local.remove(n,(()=>e()))))},listValues:()=>{const e=[];return Object.getOwnPropertyNames(t).forEach((t=>{e.push(t)})),e},isWorking:async()=>new Promise(((e,t)=>{let n=0;const a=Date.now(),o="foo",r={};r[o]={origin:"normal",value:a};const i=()=>{d&&m(d),d=null},l=e=>{++n<=5?(s.warn("storage:",e||"storage set/get test failed!"),E(g,n*n*100)):(s.warn("storage: storage set/get test finally failed!"),c())},c=()=>{d&&(i(),t())};let d=E((()=>{d=null,c()}),18e4)
;const g=()=>{s.log("Storage: test -> start");const t=Date.now();_.local.set(r,(()=>{s.log("Storage: test -> set after "+(Date.now()-t)+"ms"),_.local.get(o,(n=>(s.log("Storage: test -> get after "+(Date.now()-t)+"ms"),n&&n[o]?n[o].value!==a?l("read value is different "+JSON.stringify(n[o])+" != "+JSON.stringify(a)):R.lastError?l(R.lastError&&R.lastError.message||"lastError is set"):void _.local.remove(o,(()=>{s.log("Storage: test -> remove after "+(Date.now()-t)+"ms"),d&&(i(),e())
})):l("read value is"+JSON.stringify(n)))))}))};g()}))};return{init:async()=>{if(!e){e=!0;const n=e=>{t={},e&&Object.keys(e).forEach((n=>{const a=e[n];a&&a.hasOwnProperty("origin")&&a.hasOwnProperty("value")?t[n]=a.value:t[n]=a}))};await new Promise((e=>_.local.get(null,(t=>{n(t),e()}))))}},clean:async()=>{e=!1,t={}},options:{},methods:a}})();let U;const F={chromeStorage:z},$=async()=>U?(U.isWorking||Promise.resolve)():new Promise(((e,t)=>{E((async()=>{try{await $(),e()}catch(e){t()}}),1e3)
})),H={secure:{},setValue:(e,t)=>U.setValue(e,t),setValues:e=>U.setValues(e),getValue:(e,t)=>U.getValue(e,t),deleteAll:()=>U.deleteAll(),deleteValue:e=>U.deleteValue(e),listValues:()=>U.listValues(),isWorking:$,migrate:async(e,t,n)=>{const a=F[e],o=F[t],r=n||{};if(!a||!o){const n="Migration: unknown storage implementation(s) ";throw s.error(n,e,t),n}await q(e,"init"),await q(t,"init"),await Promise.all(a.methods.listValues().map((async e=>{const t=a.methods.getValue(e)
;r.drop&&await a.methods.deleteValue(e),void 0!==t&&await o.methods.setValue(e,t)}))),await q(t,"clean"),await q(e,"clean")},init:async()=>{s.debug("Storage: use "+C);const e=F[C];U=e.methods,e.init&&await e.init()},factoryReset:()=>H.deleteAll(),isWiped:async()=>!1,setVersion:async(e,t)=>{await H.setValue(D,e),t&&await H.setValue(T,t)},getVersion:async e=>await H.getValue(D)||e,getSchemaVersion:()=>H.getValue(T,"1.0")
},X=H,B=chrome.runtime.id.substr(0,4),G=["dhdgffkkebhmkfjojejmpbldmpobfkfo","gcalenpjmijncebpfijmoaglllgpjagf","iikmkjmpaadaobahmlepeloendndfphd","fcmfnpggmnlmfebfghbfnillijihnkoh","heiflgcdlcilkmbminjohdnmejohiblb"],K=["lieo"],{runtime:Q}=chrome,Y={},Z={},ee={configMode:0,logLevel:"hohm"===B?100:0,externalExtensionIds:[...G]},te={},ne=e=>{let t,n=X.getValue(W,{});return n instanceof Object||(n={}),void 0!==(t=n[e])?t:"function"==typeof(t=ee[e])?t():t},ae=(e,t)=>{let n=X.getValue(W,{})
;n instanceof Object||(n={});const a=ne(e);n[e]=t;const o=X.setValue(W,n),r=Z[e];return r&&JSON.stringify(a)!=JSON.stringify(t)&&r.forEach((n=>{try{n(e,a,t,o)}catch(e){s.warn("config: changeListener error",e)}})),o};let se={};(()=>{let e;if(M&&(e=M.getItem(x)))try{se=JSON.parse(c(e))}catch(e){}})();const oe=e=>{let t;return void 0!==(t=se[e])?t:te[e]},re=(e,t)=>{const n=oe(e);void 0===t?delete se[e]:se[e]=t,M&&M.setItem(x,(e=>{let t=""
;for(let n=0;n<e.length;n++)t+=String.fromCharCode(255&e.charCodeAt(n));return d(t)})(JSON.stringify(se)));const a=Z[e];a&&JSON.stringify(n)!=JSON.stringify(t)&&a.forEach((a=>{try{a(e,n,t)}catch(e){s.warn("config: changeListener error",e)}}))},ie={initialized:!1,values:{},snapshot:{},init:async()=>{const e={};Object.defineProperty(ie,"snapshot",{get:function(){return{...ie.values}},enumerable:!0}),Object.keys(ee).forEach((t=>{Object.defineProperty(e,t,{get:function(){return ne(t)},
set:function(e){ae(t,e)},enumerable:!0})})),Object.keys(te).forEach((t=>{Object.defineProperty(e,t,{get:function(){return oe(t)},set:function(e){re(t,e)},enumerable:!0})})),ie.values=e,ie.initialized=!0},getValue:e=>te.hasOwnProperty(e)?oe(e):ne(e),setValue:async(e,t)=>te.hasOwnProperty(e)?await re(e,t):await ae(e,t),getDefaults:()=>ee,addChangeListener:(e,t)=>{var n;(n=e,Array.isArray(n)?n:[n]).forEach((e=>{let n=Z[e];n||(n=Z[e]=[]),n.push(t)}))}},le=ie;let ce
;const{permissions:de,runtime:ge}=chrome,me=ge.getManifest(),{host_permissions:ue,permissions:fe}=me,he=(fe||[]).concat(ue||[]).filter((e=>e.startsWith("https://")||e.startsWith("http://")||e.startsWith("*://"))),pe="https://vscode.dev/?connectTo=tampermonkey",{runtime:ye,action:we,tabs:be,webNavigation:ve,scripting:Ee}=chrome,Ve=async e=>{e?(we.setIcon({path:{16:"images/icon_forbidden.png",24:"images/icon24_forbidden.png",32:"images/icon32_forbidden.png",48:"images/icon48_forbidden.png",
128:"images/icon128_forbidden.png"}}),we.setTitle({title:"Tampermonkey Editors - has no access to vscode.dev"})):(we.setIcon({path:{16:"images/icon.png",24:"images/icon24.png",32:"images/icon32.png",48:"images/icon48.png",128:"images/icon128.png"}}),we.setTitle({title:"Tampermonkey Editors"}))};(async e=>{e.oninstall=()=>e.skipWaiting(),(async()=>{ve.onCommitted.addListener((async e=>{const{url:t,tabId:n}=e;t.startsWith(pe)&&(Ee.executeScript({files:["content.js"],target:{tabId:n,frameIds:[0]},
injectImmediately:!0,world:"ISOLATED"}),Ee.executeScript({files:["page.js"],target:{tabId:n,frameIds:[0]},injectImmediately:!0,world:"MAIN"}))}));const e=async(t,a)=>{if(n)return await n,e(t,a);{let e=()=>null;n=new Promise((t=>e=t)),n.then((()=>n=void 0));const o=await(async e=>{const t=!K.length||K.includes(B)?G:le.values.externalExtensionIds;return await Promise.all(t.map((t=>{if(void 0===Y[t])return Y[t]=!1,new Promise((n=>{try{const a=Q.connect(t),s=Math.random().toString(36).substr(2,5)
;a.postMessage({method:"userscripts",action:"options",messageId:s,activeUrls:e}),a.onMessage.addListener((e=>{Q.lastError,e||(delete Y[t],a.disconnect()),e&&e.messageId===s&&e.allow&&e.allow.includes("list")&&(Y[t]=a),n()})),a.onDisconnect.addListener((()=>{Q.lastError,delete Y[t],n()}))}catch(e){s.debug(`unable to talk to ${t}`,e),n()}}))}))),Object.keys(Y).filter((e=>!1!==Y[e])).map((e=>({id:e,port:Y[e]})))})([pe]);if(!o.length)return a({error:"no extension to talk to"}),void e()
;const[{id:r,port:i}]=o;s.log(`Found extension ${r}`);const l=t=>{a(t),i.onMessage.removeListener(l),e()};i.onMessage.addListener(l),i.postMessage({method:t.method,...t.args}),await n,n=void 0}};let t;ye.onMessage.addListener(((t,n,a)=>(e(t,a),!0))),we.onClicked.addListener((async()=>{if(ye.lastError,!t){const e=await(async()=>await new Promise((e=>{de.request({origins:he},(t=>{ge.lastError&&console.error(ge.lastError),e(t)}))})))();if(!e)return;t=e,Ve(!t)}be.query({url:pe+"*"},(e=>{
e&&e.length&&e[0].id?be.update(e[0].id,{active:!0},(()=>ye.lastError)):be.create({url:pe,active:!0},(()=>ye.lastError))}))}));let n=(async()=>{await X.init(),await le.init(),s.set(le.values.logLevel)})();(async()=>{t=await(async e=>(void 0===ce&&(ce=await new Promise((t=>{de.contains({origins:[e]},(e=>t(e)))}))),ce))(pe),Ve(!t)})(),await n,n=void 0,s.log("Tampermonkey Editors initialization done")})()})(self)})();